name: scan_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  camera: ^0.11.2
  permission_handler: ^12.0.1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  riverpod: ^2.6.1
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  google_generative_ai: ^0.4.7
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
