name: hungryowl
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  camera: ^0.11.2
  permission_handler: ^12.0.1
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  riverpod: ^2.6.1
  http: ^1.4.0
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_dotenv: ^5.2.1
  shared_preferences: ^2.5.3
  sembast: ^3.8.5+1
  uuid: ^4.5.1
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  firebase_core: ^4.0.0
  firebase_ai: ^3.1.0
  url_launcher: ^6.3.2
  in_app_review: ^2.0.10
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/owl.png
    - assets/brown_owl.png
